### ISSUE TITLE
method missing when try to extract a srem

### ISSUE THREAD

**Issue by dbcesar** [rock-core/tools-pocolog#15]
I'm having problems when try to extract a single stream from a log file.

My input:
```
pocolog --streams apriltags_detector_front.detected_corners --extract ~/Desktop/test.0.log
apriltags_detector_front.detected_corners
```

And then I have this:
```

/home/diego/dev.bir/tools/pocolog/bin/pocolog:561:in `method_missing': undefined method `streams' for #<Pocolog::Config:0x000000025c73b0 @files=[]> (NoMethodError)
	from /home/diego/dev.bir/tools/pocolog/bin/pocolog:668:in `block (3 levels) in <main>'
	from /home/diego/dev.bir/tools/pocolog/bin/pocolog:663:in `each'
	from /home/diego/dev.bir/tools/pocolog/bin/pocolog:663:in `block (2 levels) in <main>'
	from /home/diego/.rbenv/versions/2.3.1/lib/ruby/2.3.0/optparse.rb:1540:in `block in parse_in_order'
	from /home/diego/.rbenv/versions/2.3.1/lib/ruby/2.3.0/optparse.rb:1527:in `catch'
	from /home/diego/.rbenv/versions/2.3.1/lib/ruby/2.3.0/optparse.rb:1527:in `parse_in_order'
	from /home/diego/.rbenv/versions/2.3.1/lib/ruby/2.3.0/optparse.rb:1521:in `order!'
	from /home/diego/.rbenv/versions/2.3.1/lib/ruby/2.3.0/optparse.rb:1513:in `order'
	from /home/diego/dev.bir/tools/pocolog/bin/pocolog:696:in `<main>'
```

Am I missing something?

**Comment by doudou** [comment]
> Am I missing something?

You're missing that the CLI implementation is horrible.

It's `--extract FILE --stream STREAM`

**Comment by dbcesar** [comment]
Thx. However it only works if you do `--stream STREAM:start:end` . Otherwise it fails with:

```
/home/diego/dev.bir/tools/pocolog/bin/pocolog:667:in `block (3 levels) in <main>': undefined method `-' for nil:NilClass (NoMethodError)
	from /home/diego/dev.bir/tools/pocolog/bin/pocolog:663:in `each'
	from /home/diego/dev.bir/tools/pocolog/bin/pocolog:663:in `block (2 levels) in <main>'
	from /home/diego/.rbenv/versions/2.3.1/lib/ruby/2.3.0/optparse.rb:1540:in `block in parse_in_order'
	from /home/diego/.rbenv/versions/2.3.1/lib/ruby/2.3.0/optparse.rb:1527:in `catch'
	from /home/diego/.rbenv/versions/2.3.1/lib/ruby/2.3.0/optparse.rb:1527:in `parse_in_order'
	from /home/diego/.rbenv/versions/2.3.1/lib/ruby/2.3.0/optparse.rb:1521:in `order!'
	from /home/diego/.rbenv/versions/2.3.1/lib/ruby/2.3.0/optparse.rb:1513:in `order'
	from /home/diego/dev.bir/tools/pocolog/bin/pocolog:695:in `<main>'
```
