### ISSUE TITLE
Run pocolog on incomplete log files

### ISSUE THREAD

**Issue by mihaelapopescu** [rock-core/tools-pocolog#37]
Hey,

I'm trying to extract a log file which has a corrupted last entry and I'm getting the following error:

```
pocolog human_pose_est_Logger.0.log 
pocolog.rb[INFO]: building index human_pose_est_Logger.0.log ...

Traceback (most recent call last):
	14: from /opt/workspace/tools/pocolog/bin/pocolog:715:in `<main>'
	13: from /opt/workspace/tools/pocolog/bin/pocolog:578:in `execute'
	12: from /opt/workspace/tools/pocolog/bin/pocolog:578:in `new'
	11: from /opt/workspace/tools/pocolog/bin/pocolog:112:in `initialize'
	10: from /opt/workspace/tools/pocolog/bin/pocolog:112:in `new'
	 9: from /opt/workspace/tools/pocolog/lib/pocolog/logfiles.rb:121:in `initialize'
	 8: from /opt/workspace/tools/pocolog/lib/pocolog/logfiles.rb:262:in `load_stream_info'
	 7: from /opt/workspace/tools/pocolog/lib/pocolog/logfiles.rb:262:in `map'
	 6: from /opt/workspace/tools/pocolog/lib/pocolog/logfiles.rb:263:in `block in load_stream_info'
	 5: from /opt/workspace/tools/pocolog/lib/pocolog/logfiles.rb:320:in `load_stream_info_from_file'
	 4: from /opt/workspace/tools/pocolog/lib/pocolog/logfiles.rb:376:in `rebuild_and_load_index'
	 3: from /opt/workspace/tools/pocolog/lib/pocolog/format/v2.rb:391:in `rebuild_index_file'
	 2: from /opt/workspace/tools/pocolog/lib/pocolog/file_index_builder.rb:39:in `file_index_builder'
	 1: from /opt/workspace/tools/pocolog/lib/pocolog/block_stream.rb:412:in `read_data_block_header'
/opt/workspace/tools/pocolog/lib/pocolog/block_stream.rb:329:in read_payload: expected to read 21 bytes but got 20 (Pocolog::NotEnoughData)
``` 

Is it possible to update pocolog, such that it doesn't fail if the last entry of a log file is invalid/incomplete? Thanks!

**Comment by doudou** [comment]
Yes, it is possible :P. But the general backlog puts this low on the priority list.

If you run pocolog-repair on the file(s), it will create a set of new files without the issue, that you can load easily.

**Comment by mihaelapopescu** [comment]
Thank you, this solves my problem. :+1:
