### ISSUE TITLE
Missing regeneration of index files

### ISSUE THREAD

**Issue by saarnold** [rock-core/tools-pocolog#7]
Currently when replaying logs, containing already existing index files, errors like this occur:
```
/tools/pocolog/lib/pocolog/file.rb:745:in `data_header': payload was supposed to be  bytes, but found 1422563323 (RuntimeError)
```
After the last update of the stream aligner rock-core/tools-pocolog#6 it seems necessary to recreate existing index files. This is not triggered automatically.

**Comment by doudou** [comment]
Complete backtrace, please.

**Comment by doudou** [comment]
And ideally a log file / index file combination which triggers the problem ...

**Comment by saarnold** [comment]
Backtrace:
```
/home/sirius/master/tools/pocolog/lib/pocolog/file.rb:745:in `data_header': payload was supposed to be  bytes, but found 449 (RuntimeError)
	from /home/sirius/master/tools/pocolog/lib/pocolog/data_reader.rb:96:in `data_header'
	from /home/sirius/master/tools/pocolog/lib/pocolog/data_reader.rb:208:in `rescue in read_one_raw_data_sample'
	from /home/sirius/master/tools/pocolog/lib/pocolog/data_reader.rb:199:in `read_one_raw_data_sample'
	from /home/sirius/master/tools/orocos.rb/lib/orocos/log/task_context.rb:364:in `raw_read'
	from /home/sirius/master/tools/orocos.rb/lib/orocos/async/log/ports.rb:104:in `raw_last_sample'
	from /home/sirius/master/tools/orocos.rb/lib/orocos/async/task_context_proxy.rb:235:in `reachable!'
	from /home/sirius/master/tools/orocos.rb/lib/orocos/async/task_context_proxy.rb:850:in `block in connect_port'
	from /home/sirius/master/tools/utilrb/lib/utilrb/event_loop.rb:158:in `call'
	from /home/sirius/master/tools/utilrb/lib/utilrb/event_loop.rb:158:in `call'
	from /home/sirius/master/tools/utilrb/lib/utilrb/event_loop.rb:615:in `block in step'
	from /home/sirius/master/tools/utilrb/lib/utilrb/event_loop.rb:704:in `call'
	from /home/sirius/master/tools/utilrb/lib/utilrb/event_loop.rb:704:in `handle_errors'
	from /home/sirius/master/tools/utilrb/lib/utilrb/event_loop.rb:615:in `step'
	from /home/sirius/master/tools/utilrb/lib/utilrb/event_loop.rb:521:in `exec'
	from /home/sirius/master/tools/utilrb/lib/utilrb/event_loop.rb:541:in `wait_for'
	from /home/sirius/master/tools/orocos.rb/lib/orocos/async/object_base.rb:347:in `wait'
	from /home/sirius/master/tools/orocos.rb/lib/orocos/async/log/ports.rb:96:in `to_proxy'
	from /home/sirius/master/gui/vizkit/lib/vizkit/vizkit_items.rb:969:in `port_from_items'
	from /home/sirius/master/gui/vizkit/lib/vizkit/vizkit_items.rb:485:in `context_menu'
	from /home/sirius/master/gui/vizkit/lib/vizkit/tree_view.rb:15:in `block in setup_tree_view'
	from /home/sirius/master/.gems/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `call'
	from /home/sirius/master/.gems/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /home/sirius/master/.gems/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `qt_metacall'
	from /home/sirius/master/.gems/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `method_missing'
	from /home/sirius/master/.gems/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `exec'
	from /home/sirius/master/gui/vizkit/lib/vizkit/vizkit.rb:137:in `exec'
	from /home/sirius/master/gui/vizkit/bin/rock-replay:105:in `replay'
	from /home/sirius/master/gui/vizkit/bin/rock-replay:150:in `<main>'
	from /home/sirius/master/tools/utilrb/lib/utilrb/event_loop.rb:622:in `step'
	from /home/sirius/master/tools/utilrb/lib/utilrb/event_loop.rb:521:in `exec'
	from /home/sirius/master/tools/utilrb/lib/utilrb/event_loop.rb:541:in `wait_for'
	from /home/sirius/master/tools/orocos.rb/lib/orocos/async/object_base.rb:347:in `wait'
	from /home/sirius/master/tools/orocos.rb/lib/orocos/async/log/ports.rb:96:in `to_proxy'
	from /home/sirius/master/gui/vizkit/lib/vizkit/vizkit_items.rb:969:in `port_from_items'
	from /home/sirius/master/gui/vizkit/lib/vizkit/vizkit_items.rb:485:in `context_menu'
	from /home/sirius/master/gui/vizkit/lib/vizkit/tree_view.rb:15:in `block in setup_tree_view'
	from /home/sirius/master/.gems/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `call'
	from /home/sirius/master/.gems/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:2470:in `invoke'
	from /home/sirius/master/.gems/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `qt_metacall'
	from /home/sirius/master/.gems/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `method_missing'
	from /home/sirius/master/.gems/gems/qtbindings-4.8.6.2/lib/Qt/qtruby4.rb:479:in `exec'
	from /home/sirius/master/gui/vizkit/lib/vizkit/vizkit.rb:137:in `exec'
	from /home/sirius/master/gui/vizkit/bin/rock-replay:105:in `replay'
	from /home/sirius/master/gui/vizkit/bin/rock-replay:150:in `<main>'
```
Example log:
https://dl.dropboxusercontent.com/u/86500405/DFKI/sb_base.0.log
As soon one does a right click on the RBS output port the error occurs.
